[package]
name = "decon-py"
description = "Python bindings for decon contamination detection"
categories = ["development-tools::ffi"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_decon"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
decon-core = { path = "../decon-core" }
pyo3.workspace = true
rayon.workspace = true
